const form=document.querySelector('#search'),status=document.querySelector('#status'),results=document.querySelector('#results');
fetch('/api/info').then(r=>r.json()).then(d=>{document.querySelector('#dataset').textContent=d.synthetic?`Inventario sintético: ${d.count} objetos ficticios. Los resultados no miden el rendimiento en TMB.`:`Inventario local: ${d.count} objetos. Laboratorio sin autenticación: utiliza únicamente datos de prueba.`}).catch(()=>{document.querySelector('#dataset').textContent='No se pudo leer el inventario.'});
form.addEventListener('submit',async event=>{
event.preventDefault();results.replaceChildren();status.className='';status.textContent='Buscando…';document.querySelector('#submit').disabled=true;
try{const body=Object.fromEntries(new FormData(form));const response=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);
status.textContent=`${data.results.length} candidatos mostrados. ${data.excluded.length} objetos excluidos por los filtros.`+(data.results.length?'':' No hay candidatos con los criterios actuales; esto no demuestra que el objeto no esté registrado.');
for(const row of data.results){const card=document.createElement('article');card.className='card';const id=document.createElement('span');id.className='id';id.textContent=row.id;const title=document.createElement('h3');title.textContent=row.description;const meta=document.createElement('small');meta.textContent=`Hallazgo: ${row.found_date??'fecha desconocida'} · ${row.found_line??'línea desconocida'}`;const score=document.createElement('small');score.textContent=`Puntuación experimental: ${row.score.toFixed(3)} · Texto: ${row.text_score.toFixed(3)}`;card.append(id,title,meta,score);results.append(card)}
}catch(error){status.className='error';status.textContent=error.message}finally{document.querySelector('#submit').disabled=false}
});
